rails associations: Private events
mahmoud717/private_eventz pull request #1
Opened 2020-10-28 11:06 UTC by mahmoud717

in this project i did the following:
I created a private events website that gives the users the ability to create an account with only username and log in and out, gives them the ability to create, attend, and cancel events, create events when they are logged in and see various events and users.

2020-10-28 17:29 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello @mahmoud717!
Great job with the implementation of the project! 👍 
Well done with the linters in 🟢 
However, we need to implement some changes to meet the basic requirements to get the project approved 💪 
Kindly check my comments below 👇  implement the changes and resubmit your project for a new code review ⏩ 
## Mandatory changes
- lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- The database scheme should have:
* [ ] the events table has column `creator_id` of type `integer`
* [x] an index for `creator_id` column is added
* [x] the events_attendation/events_users/(any other name for join table between users and events) table has column `event_id` of type `integer`
* [ ] an index for `event_id` column is added
* [ ] the events_attendation/events_users/(any other name for join table between users and events) table has column `user_id` of type `integer`
* [ ] an index for `user_id` column is added

2020-10-28 17:29 UTC, javitocor commented on README.md
> +- <code>$ bundle install</code>
I think this is not the name of the project, kindly modify it

2020-10-29 08:21 UTC, mahmoud717 commented
all the changes are done.
the scopes exist in the event model

2020-10-29 09:54 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for implementing the suggested changes
However, there are still some issues

1- I got this error when I launched the app
![Screenshot at 2020-10-29 10:41:10](https://user-images.githubusercontent.com/8848104/97551529-60eef900-19d3-11eb-810a-f4e6a85273b6.png)

2- As you can read [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png), it's required that, in the user show page, the attending events be separated in two: Past and Upcoming.
In your application, there is no distinction. Kindly add it, please

3- Read the comments left below

4- As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png), Kindly, please, **write unit and integration tests**

5- The `rubocop.yml` file is missing. Kindly set it up through that [link](https://github.com/microverseinc/linters-config/tree/master/ror)

Kindly make the suggested changes and once done, submit a new code review request
Thanks

Mael FOSSO

2020-10-29 09:54 UTC, maelfosso commented on app/controllers/events_controller.rb
> +  before_action is_logged_in? , only:[:new]
It's `:is_logged_in?` instead of `is_logged_in?`
You forgot `:`

2020-10-29 09:54 UTC, maelfosso commented on app/views/users/show.html.erb
> +            <% @user.events.where(user_id: @user.id).each do |event| %>
Such a call must not be done in the view but in the controllers.
Create in the controller a view variable that will keep that result in order to be used in the views

Also, `@user.events.where(user_id: @user.id)` can simply be written `@user.events`

2020-10-29 09:54 UTC, maelfosso commented on app/views/users/show.html.erb
> +            <% @user.event_attended.each do |event| %>
Such a call must not be done in the view but in the controllers.
Create in the controller a view variable that will keep that result in order to be used in the views

2020-10-29 13:56 UTC, rOluochKe approved these changes
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-10-29 14:00 UTC, merged